---
# tasks file for sbaerlocher.certbot

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        -  "vars"
  tags:
    - configuration
    - packages

- name: install certbot
  package: 
    name: "{{ certbot_package }}"
    state: latest
  tags:
    - packages

- name: add certbot renew cron
  cron:
    name: Certbot automatic renewal.
    job: "/usr/bin/certbot renew --quiet --no-self-upgrade"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"
  tags:
    - configuration