---
# tasks file for sbaerlocher.certbot

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/defaults.yml"
  tags:
    - configuration
    - packages

- name: Distribution | Include
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        - "distribution"
  tags:
    - configuration
    - packages

- name: install certbot
  package:
    name: "{{ certbot_packages }}"
  tags:
    - packages

- name: add certbot renew cron
  cron:
    name: "certbot renew"
    hour: "2"
    job: "/usr/bin/certbot renew --quiet --no-self-upgrade"
  tags:
    - configuration
