---
# tasks file for sbaerlocher.certbot

- name: 'add OS specific variables'
  include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - '{{ ansible_system }}.yml'
        - 'defaults.yml'
      paths:
        - 'vars'
  loop_control:
    loop_var: loop_vars
  tags:
    - configuration
    - packages

- name: 'include distribution tasks'
  include_tasks: '{{ loop_distribution }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - '{{ ansible_system }}.yml'
        - 'defaults.yml'
      paths:
        - 'distribution'
  loop_control:
    loop_var: loop_distribution
  tags:
    - configuration
    - packages

- name: 'install certbot'
  package:
    name: '{{ certbot_packages }}'
  tags:
    - packages

- name: 'create directory {{ certbot_location }}'
  file:
    path: '{{ certbot_location }}'
    state: directory
    mode: 0755

- name: 'add certbot renew cron'
  cron:
    name: 'certbot renew'
    hour: '2'
    job: '{{ certbot_cron }}'
  when: certbot_cron
  tags:
    - configuration

# Clouflare
- block:

    - name: 'install certbot DNS cloudflare'
      pip:
        name: certbot-dns-cloudflare
      tags:
        - packages

    - name: 'configure cloudflare.ini'
      copy:
        content: |
          dns_cloudflare_email = {{ certbot_cloudflare_email }}
          dns_cloudflare_api_key = {{ certbot_cloudflare_api_key }}
        dest: '{{ certbot_location }}/cloudflare.ini'
        owner: '{{ certbot_permissions_owner }}'
        group: '{{ certbot_permissions_group }}'
        mode: '{{ certbot_permissions_mode }}'
      tags:
        - configuration

  when: certbot_cloudflare_email is defined and certbot_cloudflare_api_key is defined
